package stationconnquerier

import (
	"sort"

	"github.com/Telenav/osrm-backend/integration/api/nav"
	"github.com/Telenav/osrm-backend/integration/service/oasis/connectivitymap"
	"github.com/Telenav/osrm-backend/integration/service/oasis/internal/common"
	"github.com/Telenav/osrm-backend/integration/service/oasis/spatialindexer"
	"github.com/Telenav/osrm-backend/integration/service/oasis/stationfinder/stationfindertype"
	"github.com/golang/glog"
)

// StationConnectivityQuerier implements interface of connectivitymap.Querier based on pre-build connectivity data.
type StationConnectivityQuerier struct {
	stationLocationQuerier   spatialindexer.PlaceLocationQuerier
	stationConnectivity      *connectivitymap.ConnectivityMap
	reachableStationsByStart []*common.RankedPlaceInfo
	reachableStationToEnd    map[common.PlaceID]*common.RankedPlaceInfo
	startLocation            *nav.Location
	endLocation              *nav.Location
}

// New creates connectivitymap.Querier interface which is implemented by StationConnectivityQuerier
func New(stationFinder spatialindexer.Finder, stationRanker spatialindexer.Ranker,
	stationLocationQuerier spatialindexer.PlaceLocationQuerier,
	stationConnectivity *connectivitymap.ConnectivityMap,
	start, end *nav.Location,
	currEnergyLevel, maxEnergyLevel float64) connectivitymap.Querier {

	querier := &StationConnectivityQuerier{
		stationLocationQuerier: stationLocationQuerier,
		stationConnectivity:    stationConnectivity,
		startLocation:          start,
		endLocation:            end,
	}
	querier.connectStartIntoStationGraph(stationFinder, stationRanker, start, currEnergyLevel)
	querier.connectEndIntoStationGraph(stationFinder, stationRanker, end, maxEnergyLevel)

	glog.Info("Generate StationConnectivityQuerier.\n")
	return querier
}

func (querier *StationConnectivityQuerier) connectStartIntoStationGraph(stationFinder spatialindexer.Finder, stationRanker spatialindexer.Ranker,
	start *nav.Location, currEnergyLevel float64) {
	center := nav.Location{Lat: start.Lat, Lon: start.Lon}
	nearByPoints := stationFinder.FindNearByPlaceIDs(center, currEnergyLevel, spatialindexer.UnlimitedCount)
	rankedPoints := stationRanker.RankPlaceIDsByShortestDistance(center, nearByPoints)

	querier.reachableStationsByStart = rankedPoints
	glog.Infof("Add %d stations connects Start.\n", len(querier.reachableStationsByStart))
}

func (querier *StationConnectivityQuerier) connectEndIntoStationGraph(stationFinder spatialindexer.Finder, stationRanker spatialindexer.Ranker,
	end *nav.Location, maxEnergyLevel float64) {
	center := nav.Location{Lat: end.Lat, Lon: end.Lon}
	nearByPoints := stationFinder.FindNearByPlaceIDs(center, maxEnergyLevel, spatialindexer.UnlimitedCount)
	rankedPoints := stationRanker.RankPlaceIDsByShortestDistance(center, nearByPoints)

	reachableStationToEnd := make(map[common.PlaceID]*common.RankedPlaceInfo)
	for _, rankedPointInfo := range rankedPoints {
		reachableStationToEnd[rankedPointInfo.ID] = &common.RankedPlaceInfo{
			PlaceInfo: common.PlaceInfo{
				ID:       stationfindertype.DestLocationID,
				Location: end,
			},
			Weight: rankedPointInfo.Weight,
		}
	}

	querier.reachableStationToEnd = reachableStationToEnd
	glog.Infof("Add %d stations connects End node.\n", len(querier.reachableStationToEnd))
}

// NearByStationQuery finds near by stations by given placeID and return them in recorded sequence
// Returns nil if given placeID is not found or no connectivity
// For start point, directly returns reachableStationsByStart which is generated by considering current energy level.
// For end point, return nil, no connectivity expected from end to others
// For charge stations, it retrieves connectivity from pre-build data.  If a charge station is reachable to destination/end point, it must connects that into graph.
func (querier *StationConnectivityQuerier) NearByStationQuery(placeID common.PlaceID) []*common.RankedPlaceInfo {

	if placeID == stationfindertype.OrigLocationID {
		return querier.reachableStationsByStart
	}

	if placeID == stationfindertype.DestLocationID {
		return nil
	}

	if connectivityResults, ok := querier.stationConnectivity.QueryConnectivity(placeID); ok {
		if !querier.isStationConnectsToEnd(placeID) {
			return connectivityResults
		} else {
			size := len(connectivityResults) + 1
			results := make([]*common.RankedPlaceInfo, 0, size)
			for _, result := range connectivityResults {
				results = append(results, result)
			}
			return querier.connectEndIntoGraph(placeID, results)
		}
	} else {
		// end position just find one charge station, and this charge station didn't has other conductivities.
		// this only exists theoretically or in mock environment
		if querier.isStationConnectsToEnd(placeID) {
			results := make([]*common.RankedPlaceInfo, 0, 1)
			return querier.connectEndIntoGraph(placeID, results)
		}
	}

	return nil
}

// GetLocation returns location of given station id
// Returns nil if given placeID is not found
func (querier *StationConnectivityQuerier) GetLocation(placeID common.PlaceID) *nav.Location {
	switch placeID {
	case stationfindertype.OrigLocationID:
		return querier.startLocation
	case stationfindertype.DestLocationID:
		return querier.endLocation
	default:
		return querier.stationLocationQuerier.GetLocation(placeID.String())
	}
}

func (querier *StationConnectivityQuerier) isStationConnectsToEnd(placeID common.PlaceID) bool {
	_, ok := querier.reachableStationToEnd[placeID]
	return ok
}

func (querier *StationConnectivityQuerier) connectEndIntoGraph(placeID common.PlaceID, results []*common.RankedPlaceInfo) []*common.RankedPlaceInfo {
	if queryResult4End, ok := querier.reachableStationToEnd[placeID]; ok {
		return appendIntoSortedSlice(queryResult4End, results)
	}
	return results
}

func appendIntoSortedSlice(item *common.RankedPlaceInfo, results []*common.RankedPlaceInfo) []*common.RankedPlaceInfo {

	// todo @codebear801 this code assumes result is sorted by Distance, better hide in array itself or sortStrategy
	insertIndex := sort.Search(len(results), func(i int) bool {
		return results[i].Weight.Distance > item.Weight.Distance
	})

	results = append(results, nil)
	copy(results[insertIndex+1:], results[insertIndex:])
	results[insertIndex] = item

	return results
}
