%% Call below command to convert .mmd to .png
%%  Adjust -w or -H if necessary
%% mmdc -p puppeteer-config.json -i customize-traffic-container-startup-flow-chart.mmd -o customize-traffic-container-startup-flow-chart.mmd.png

graph TD

Title[<u>OSRM Recustomize Traffic Flow Chart</u>]
Title-->Start
style Title fill:#FFF,stroke:#FFF
linkStyle 0 stroke:#FFF,stroke-width:0;

Start("Start") --> BackupNoTrafficMetrics["Backup no traffic metrics"]
BackupNoTrafficMetrics --> FirstRoundLoadDataToSharedMemory["osrm-datastore load data to shared memory"]
FirstRoundLoadDataToSharedMemory --> LaunchRoutedFromSharedMemory["launch osrm-routed with shared memory data"]


LaunchRoutedFromSharedMemory --> ConnectTrafficProxy["Run osrm-traffic-updater to pull traffic data"]

subgraph Update Traffic
ConnectTrafficProxy --> CopyNoTrafficMetrics["Copy no traffic metrics from backup"]
CopyNoTrafficMetrics --> OSRMCustomize["Run osrm-customize to apply traffic data on metrics"]
OSRMCustomize --> OSRMDataStore["Run osrm-datastore to load/switch new metrics"]
OSRMDataStore --> ConnectTrafficProxy
end

